/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketAuctionSol from "./MarketAuction.sol";
export type { marketAuctionSol };
export type { InputVerificationMock } from "./InputVerificationMock";
export type { ShadowMerchants } from "./ShadowMerchants";
