/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace InputVerificationMock {
  export type ProofRequestStruct = {
    contractChainId: BigNumberish;
    contractAddress: AddressLike;
    userAddress: AddressLike;
    ciphertextWithZKProof: BytesLike;
    extraData: BytesLike;
  };

  export type ProofRequestStructOutput = [
    contractChainId: bigint,
    contractAddress: string,
    userAddress: string,
    ciphertextWithZKProof: string,
    extraData: string
  ] & {
    contractChainId: bigint;
    contractAddress: string;
    userAddress: string;
    ciphertextWithZKProof: string;
    extraData: string;
  };
}

export interface InputVerificationMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProofRequest"
      | "proofRequests"
      | "rejectProofResponse"
      | "verifyProofRequest"
      | "verifyProofResponse"
      | "zkProofIdCounter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RejectProofResponse"
      | "VerifyProofRequest"
      | "VerifyProofResponse"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getProofRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proofRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectProofResponse",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProofRequest",
    values: [BigNumberish, AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProofResponse",
    values: [BigNumberish, BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkProofIdCounter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getProofRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectProofResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProofRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProofResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkProofIdCounter",
    data: BytesLike
  ): Result;
}

export namespace RejectProofResponseEvent {
  export type InputTuple = [zkProofId: BigNumberish];
  export type OutputTuple = [zkProofId: bigint];
  export interface OutputObject {
    zkProofId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifyProofRequestEvent {
  export type InputTuple = [
    zkProofId: BigNumberish,
    contractChainId: BigNumberish,
    contractAddress: AddressLike,
    userAddress: AddressLike,
    ciphertextWithZKProof: BytesLike,
    extraData: BytesLike
  ];
  export type OutputTuple = [
    zkProofId: bigint,
    contractChainId: bigint,
    contractAddress: string,
    userAddress: string,
    ciphertextWithZKProof: string,
    extraData: string
  ];
  export interface OutputObject {
    zkProofId: bigint;
    contractChainId: bigint;
    contractAddress: string;
    userAddress: string;
    ciphertextWithZKProof: string;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifyProofResponseEvent {
  export type InputTuple = [
    zkProofId: BigNumberish,
    ctHandles: BytesLike[],
    signatures: BytesLike[]
  ];
  export type OutputTuple = [
    zkProofId: bigint,
    ctHandles: string[],
    signatures: string[]
  ];
  export interface OutputObject {
    zkProofId: bigint;
    ctHandles: string[];
    signatures: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InputVerificationMock extends BaseContract {
  connect(runner?: ContractRunner | null): InputVerificationMock;
  waitForDeployment(): Promise<this>;

  interface: InputVerificationMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProofRequest: TypedContractMethod<
    [zkProofId: BigNumberish],
    [InputVerificationMock.ProofRequestStructOutput],
    "view"
  >;

  proofRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string] & {
        contractChainId: bigint;
        contractAddress: string;
        userAddress: string;
        ciphertextWithZKProof: string;
        extraData: string;
      }
    ],
    "view"
  >;

  rejectProofResponse: TypedContractMethod<
    [zkProofId: BigNumberish, arg1: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyProofRequest: TypedContractMethod<
    [
      contractChainId: BigNumberish,
      contractAddress: AddressLike,
      userAddress: AddressLike,
      ciphertextWithZKProof: BytesLike,
      extraData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  verifyProofResponse: TypedContractMethod<
    [
      zkProofId: BigNumberish,
      ctHandles: BytesLike[],
      signature: BytesLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  zkProofIdCounter: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProofRequest"
  ): TypedContractMethod<
    [zkProofId: BigNumberish],
    [InputVerificationMock.ProofRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string] & {
        contractChainId: bigint;
        contractAddress: string;
        userAddress: string;
        ciphertextWithZKProof: string;
        extraData: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectProofResponse"
  ): TypedContractMethod<
    [zkProofId: BigNumberish, arg1: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProofRequest"
  ): TypedContractMethod<
    [
      contractChainId: BigNumberish,
      contractAddress: AddressLike,
      userAddress: AddressLike,
      ciphertextWithZKProof: BytesLike,
      extraData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProofResponse"
  ): TypedContractMethod<
    [
      zkProofId: BigNumberish,
      ctHandles: BytesLike[],
      signature: BytesLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zkProofIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "RejectProofResponse"
  ): TypedContractEvent<
    RejectProofResponseEvent.InputTuple,
    RejectProofResponseEvent.OutputTuple,
    RejectProofResponseEvent.OutputObject
  >;
  getEvent(
    key: "VerifyProofRequest"
  ): TypedContractEvent<
    VerifyProofRequestEvent.InputTuple,
    VerifyProofRequestEvent.OutputTuple,
    VerifyProofRequestEvent.OutputObject
  >;
  getEvent(
    key: "VerifyProofResponse"
  ): TypedContractEvent<
    VerifyProofResponseEvent.InputTuple,
    VerifyProofResponseEvent.OutputTuple,
    VerifyProofResponseEvent.OutputObject
  >;

  filters: {
    "RejectProofResponse(uint256)": TypedContractEvent<
      RejectProofResponseEvent.InputTuple,
      RejectProofResponseEvent.OutputTuple,
      RejectProofResponseEvent.OutputObject
    >;
    RejectProofResponse: TypedContractEvent<
      RejectProofResponseEvent.InputTuple,
      RejectProofResponseEvent.OutputTuple,
      RejectProofResponseEvent.OutputObject
    >;

    "VerifyProofRequest(uint256,uint256,address,address,bytes,bytes)": TypedContractEvent<
      VerifyProofRequestEvent.InputTuple,
      VerifyProofRequestEvent.OutputTuple,
      VerifyProofRequestEvent.OutputObject
    >;
    VerifyProofRequest: TypedContractEvent<
      VerifyProofRequestEvent.InputTuple,
      VerifyProofRequestEvent.OutputTuple,
      VerifyProofRequestEvent.OutputObject
    >;

    "VerifyProofResponse(uint256,bytes32[],bytes[])": TypedContractEvent<
      VerifyProofResponseEvent.InputTuple,
      VerifyProofResponseEvent.OutputTuple,
      VerifyProofResponseEvent.OutputObject
    >;
    VerifyProofResponse: TypedContractEvent<
      VerifyProofResponseEvent.InputTuple,
      VerifyProofResponseEvent.OutputTuple,
      VerifyProofResponseEvent.OutputObject
    >;
  };
}
