/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInputVerification } from "./IInputVerification";
export type { MarketAuction } from "./MarketAuction";
