/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInputVerification,
  IInputVerificationInterface,
} from "../../../contracts/MarketAuction.sol/IInputVerification";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "zkProofId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "contractChainId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "ciphertextWithZKProof",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "extraData",
        type: "bytes",
      },
    ],
    name: "VerifyProofRequest",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "contractChainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "ciphertextWithZKProof",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "extraData",
        type: "bytes",
      },
    ],
    name: "verifyProofRequest",
    outputs: [
      {
        internalType: "uint256",
        name: "zkProofId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInputVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IInputVerificationInterface {
    return new Interface(_abi) as IInputVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInputVerification {
    return new Contract(address, _abi, runner) as unknown as IInputVerification;
  }
}
